# Generated by Django 4.2.5 on 2023-09-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.IntegerField()),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Datas',
        ),
    ]
