# Generated by Django 4.2.5 on 2023-10-01 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_employees_delete_datas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employees',
            new_name='Users',
        ),
    ]
